output: C2A1E8_Employee.o C2A1E8_main-Driver.o
	g++ C2A1E8_Employee.o C2A1E8_main-Driver.o -o output

C2A1E8_Employee.o: C2A1E8_Employee.cpp C2A1E8_Employee.h
	g++ -c C2A1E8_Employee.cpp

C2A1E8_main-Driver.o: C2A1E8_main-Driver.cpp
	g++ -c C2A1E8_main-Driver.cpp
