output: C2A3E3_RecordOpinions.o C2A3E3_main-Driver.o
	gcc  $?  -o $@


C2A3E3_main-Driver.o: C2A3E3_main-Driver.c
	gcc -c C2A3E3_main-Driver.c

C2A3E3_RecordOpinions.o: C2A3E3_RecordOpinions.c
	gcc -c C2A3E3_RecordOpinions.c



run:
	output.exe
